appname = casibase
httpport = 14000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = mysql
dataSourceName = root:123@tcp(localhost:3306)/
dbName = casibase
redisEndpoint =
guacamoleEndpoint = 127.0.0.1:4822
isDemoMode = false
logPostOnly = true
landingFolder =
#我注册时的
casdoorEndpoint = http://localhost:8000
clientId = "123"
# clientId = af6b5aa958822fb9dc33
clientSecret = 123
casdoorOrganization = "casibase"
casdoorApplication = "app-casibase"
cacheDir = "C:/casibase_cache"
appDir = ""
isLocalIpDb = false
audioStorageProvider = ""
providerDbName = ""
socks5Proxy = "127.0.0.1:10808"
publicDomain = ""
adminDomain = ""

